### ISSUE TITLE
please tag a release and make it available for download as tar.gz/whatever

### ISSUE THREAD

**Issue by blshkv** [mortoray/shelljob#4]
Could you please release it? There is no source tar ball at the moment

**Comment by mortoray** [comment]
What would be included in the tarball?

**Comment by blshkv** [comment]
you need to read a documentation for that. I guess it will be the same list of files including setup.py. You just need to tag it

**Comment by blshkv** [comment]
the proper release should be available here: https://github.com/mortoray/shelljob/releases as 0.6.2.tar.gz or something

**Comment by mortoray** [comment]
done. I'll try to remember for future releases.
